# permissions for end users to view overkubes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: overkube-viewer-role
rules:
- apiGroups:
  - cache.my.domain
  resources:
  - overkubes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.my.domain
  resources:
  - overkubes/status
  verbs:
  - get
