# permissions for end users to edit overkubes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: overkube-editor-role
rules:
- apiGroups:
  - cache.my.domain
  resources:
  - overkubes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.my.domain
  resources:
  - overkubes/status
  verbs:
  - get
